apiVersion: v1
kind: Namespace
metadata:
  name: devops
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-devops-cm
  namespace: devops
data:
  USERNAME: "cmd"
  ENDPOINT: "http://api.google.com/v1"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-devops-sc
  namespace: devops
type: Opaque
stringData:
  APIKEY: "123456789abcde"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dp
  namespace: devops
  labels:
    app: mi-app-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-devops
  template:
    metadata:
      labels:
        app: backend-devops
    spec:
      containers:
      - name: backend
        image: carlosmarind/backend-node
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "3000"
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-devops-cm
              key: USERNAME
              optional: true
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: backend-devops-sc
              key: APIKEY
              optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: devops
  labels:
    app: mi-app-devops
spec:
  selector:
    app: backend-devops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-backend
  namespace: devops
spec:
  ingressClassName: nginx
  rules:
  - host: app.devops.cl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-svc
            port:
              number: 80
