services:
  wp:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=wordpress_pass
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=wordpress_pass
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=wordpress_root
volumes:
  db_data:
